addons: {chrome: stable}
dart: [dev, stable]
dist: xenial
env: [PLATFORM=browser, PLATFORM=vm]
language: dart
notifications: {email: false}

install: pub get
script: pub run grinder test --platform=${PLATFORM}
after_success: pub run grinder coverage
