language: dart
dart: stable
sudo: false

# before_script:
# - pub run coverage:collect_coverage --out=var/coverage.json
# after_script:
# - pub run coverage:format_coverage --in=var/coverage.json --lcov --out=var/coverage.lcov
